## MULTIPART (MultipartProperties)
# Enable multipart uploads
#spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
#spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
#file.upload-dir=/Users/bojana.koteska/Downloads
#file.upload-dir=/home/debian/GaussianAPIfiles
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path=/
server.forward-headers-strategy=native
springdoc.packagesToScan=com.example.GaussianAPI.controller

